<?php
  echo $this->inlineScript(\Laminas\View\Helper\HeadScript::FILE, 'openurl.js', 'SET');
  $classes = '';
  if ($this->openUrlEmbed) {
    $classes = "fulltext";
  } elseif ($this->openUrlWindow) {
    $classes = 'fulltext openUrlWindow window_settings:' . $this->escapeHtmlAttr($this->openUrlWindow);
  }
  if (!empty($classes)) {
    $class = ' class="' . $classes . '"';
    $class_ib = ' class="imagebased ' . $classes . '"';
  } else {
    $class = $class_ib = '';
  }
?>
<span class="openUrlControls<?php if ($this->openUrlEmbed): ?> openUrlEmbed<?php if ($this->openUrlEmbedAutoLoad): ?> openUrlEmbedAutoLoad<?php endif; ?><?php endif; ?>">

<?//IF NOT LOGGED IN - FORCE LOGIN ?>
<?php $loggedIn = $this->auth()->getManager()->isLoggedIn();
      $account = $this->auth()->getManager(); ?>
 <?php if (!$loggedIn):?>
   <?php //DISPLAY LOGIN OR INST. LOGIN? ?>
   <?php if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))):?>
      <?php $sessionInitiator = $account->getSessionInitiator($this->url('content-page',['page'=>'redir']) . "?" . $this->resolverUrl) ?>
      <a <?=$class?> href="<?=$sessionInitiator?>"><button type="button" class="btn btn-primary btn-primary-reshare"><?=$this->transEsc('Request')?></button></a>
      <?php //REMOVE -- $sessionInitiator = $account->getSessionInitiator($this->url('content-page',['page'=>'redir']) . "?" . $this->resolverUrl) ?>
   <?php else: ?> 
      <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox class="modal-link" title="login"><button type="button" class="btn btn-primary btn-primary-reshare"><?=$this->transEsc('Request')?></button></a>
   <?php endif; ?>
 <?//ELSE THEY ARE LOGGED IN PROCEED WITH THE OPEN URL CODE:?>
 <?php else: ?>

  <?php if (!$this->openUrlImageBasedSrc || $this->openUrlImageBasedMode == 'both'): ?>
  <a href="<?=$this->escapeHtmlAttr($this->resolverUrl)?>"<?=$class?> data-search-class-id="<?=$this->escapeHtmlAttr($this->searchClassId) ?>">
    <?php /* put the openUrl here in a span (COinS almost) so we can retrieve it later */ ?>
    <span title="<?=$this->escapeHtmlAttr($this->openUrl)?>" class="openUrl"></span>
    <?php if ($this->openUrlGraphic): ?>
      <?php
        $style = '';
        if ($this->openUrlGraphicWidth) {
          $style .= 'width:' . $this->escapeHtmlAttr($this->openUrlGraphicWidth) . 'px;';
        }
        if ($this->openUrlGraphicHeight) {
          $style .= 'height:' . $this->escapeHtmlAttr($this->openUrlGraphicHeight) . 'px;';
        }
      ?>
      <img src="<?=$this->escapeHtmlAttr($this->openUrlGraphic)?>" alt="<?=$this->transEscAttr('Get full text')?>" style="<?=$style?>" />
    <?php else: ?>
     <button type="button" class="btn btn-primary btn-primary-reshare"><?=$this->transEsc('Request')?></button>
    <?php endif; ?>
  </a>
  <?php endif; ?>

  <?php if ($this->openUrlImageBasedSrc): ?>
    <?php $ibOpenUrl = $this->openUrlImageBasedOverride ? $this->openUrlImageBasedOverride : $this->openUrl; ?>
    <a href="<?=$this->escapeHtmlAttr($this->openUrlBase . '?' . $ibOpenUrl)?>"<?=$class_ib?>>
      <span title="<?=$this->escapeHtmlAttr($ibOpenUrl)?>" class="openUrl"></span>
      <img data-recordid="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" src="<?=$this->escapeHtmlAttr($this->openUrlImageBasedSrc)?>" alt="<?=$this->transEscAttr('Get full text')?>" />
    </a>
  <?php endif; ?>
</span>

<?php if ($this->openUrlEmbed): ?>
  <div class="resolver hidden"><?=$this->transEsc('Loading')?>...</div>
<?php endif; ?>

<?php endif; //END ELSE LOGGED IN ?>
