<footer class="hidden-print" style="border-top:0px">
  <div class="footer-container">
    <div class="footer-column">
      <p><strong></strong></p>
      <ul>
      </ul>
    </div>
    <div class="footer-column">
      <p><strong></strong></p>
      <ul>
      </ul>
    </div>
    <div class="footer-column">
      <p><strong></strong></p>
      <ul>
      </ul>
    </div>
  </div>
  <div class="poweredby">
    <?=$this->layout()->poweredBy ?>
  </div>
</footer>
